version: "3"

networks:
    broker-communication:
    admin-db:
    admin-server:

services:
    mqtt-broker:
        image: eclipse-mosquitto:latest
        networks:
            - broker-communication
        ports:
            - 1883:1883

    client:
        build: ./client
        depends_on:
            - mqtt-broker
        networks:
            - broker-communication
        tty: true
        stdin_open: true

    # TODO solve dependency to admin
    server:
        build: ./server
        depends_on:
            - mqtt-broker
            - admin
        networks:
            - broker-communication
            - admin-server
        # REMOVE ME
        tty: true

    # TODO solve dependency to database
    admin:
        build: ./admin
        depends_on:
            - database
        networks:
            - admin-db
            - admin-server
        tty: true
        stdin_open: true
        ports:
            - "5001:5001"

    database:
        image: mysql:5.7
        volumes:
            - ./database:/docker-entrypoint-initdb.d/:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: expenditure_db
            MYSQL_USER: my_user
            MYSQL_PASSWORD: my_password
        ports:
            - "32000:3306"
        networks:
            - admin-db
