version: "3"

networks:
    broker-communication:

services:
    mqtt-broker:
        image: eclipse-mosquitto:latest
        networks:
            - broker-communication
        ports:
            - 1883:1883

    client:
        build: ./client
        depends_on:
            - mqtt-broker
        networks:
            - broker-communication
        tty: true
        stdin_open: true

    server:
        build: ./server
        depends_on:
            - mqtt-broker
        networks:
            - broker-communication
        # REMOVE ME
        tty: true

    database:
        image: mysql:5.7
        volumes:
            - ./database:/docker-entrypoint-initdb.d/:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: expenditure_db
            MYSQL_USER: my_user
            MYSQL_PASSWORD: my_password
        ports:
            - "32000:3306"
