version: "3"

networks:
    broker-communication:
    admin-db:
    admin-server:
    visual-db:

services:
    mqtt-broker:
        image: eclipse-mosquitto:latest
        networks:
            - broker-communication
        ports:
            - 1883:1883

    client:
        image: laurentiustefan97/idp:client
        depends_on:
            - mqtt-broker
        networks:
            - broker-communication
        tty: true
        stdin_open: true

    server:
        image: laurentiustefan97/idp:server
        depends_on:
            - mqtt-broker
            - admin
        networks:
            - broker-communication
            - admin-server
        tty: true

    admin:
        image: laurentiustefan97/idp:admin
        depends_on:
            - database
        networks:
            - admin-db
            - admin-server
        tty: true
        stdin_open: true
        ports:
            - "5001:5001"

    database:
        image: mysql:5.7
        volumes:
            - ./database:/docker-entrypoint-initdb.d/:ro
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: expenditure_db
            MYSQL_USER: my_user
            MYSQL_PASSWORD: my_password
        ports:
            - "32000:3306"
        networks:
            - admin-db
            - visual-db
        deploy:
            placement:
                constraints: [node.role == manager]

    visualizer:
        image: grafana/grafana:latest
        volumes:
            - ./grafana_data:/var/lib/grafana
        networks:
            - visual-db
        ports:
            - 80:3000
        depends_on:
            - database
        deploy:
            placement:
                constraints: [node.role == manager]
